// Mock Products (15 items)
export const mockProducts = [
  {
    id: 1,
    name: "Nike Air Max",
    price: 18999,
    category: "Shoes",
    stock: 45,
    status: "active",
    createdAt: "2025-01-10",
  },
  {
    id: 2,
    name: "Rolex Submariner",
    price: 285000,
    category: "Watches",
    stock: 3,
    status: "active",
    createdAt: "2025-01-15",
  },
  {
    id: 3,
    name: "Leather Tote Bag",
    price: 12999,
    category: "Bags",
    stock: 12,
    status: "active",
    createdAt: "2025-01-20",
  },
  {
    id: 4,
    name: "iPhone 15 Pro",
    price: 249999,
    category: "Electronics",
    stock: 8,
    status: "active",
    createdAt: "2025-01-25",
  },
  {
    id: 5,
    name: "Sony Headphones",
    price: 34999,
    category: "Electronics",
    stock: 23,
    status: "inactive",
    createdAt: "2025-02-01",
  },
  {
    id: 6,
    name: "Adidas Ultraboost",
    price: 22999,
    category: "Shoes",
    stock: 34,
    status: "active",
    createdAt: "2025-02-05",
  },
  {
    id: 7,
    name: "Gucci Belt",
    price: 45999,
    category: "Accessories",
    stock: 7,
    status: "active",
    createdAt: "2025-02-10",
  },
  {
    id: 8,
    name: "MacBook Pro",
    price: 329999,
    category: "Electronics",
    stock: 5,
    status: "active",
    createdAt: "2025-02-12",
  },
  {
    id: 9,
    name: "Samsung TV",
    price: 189999,
    category: "Electronics",
    stock: 2,
    status: "inactive",
    createdAt: "2025-02-15",
  },
  {
    id: 10,
    name: "Nike Hoodie",
    price: 8999,
    category: "Clothing",
    stock: 56,
    status: "active",
    createdAt: "2025-02-18",
  },
  {
    id: 11,
    name: "Prada Sunglasses",
    price: 32999,
    category: "Accessories",
    stock: 11,
    status: "active",
    createdAt: "2025-02-20",
  },
  {
    id: 12,
    name: "Louis Vuitton Wallet",
    price: 58999,
    category: "Accessories",
    stock: 4,
    status: "active",
    createdAt: "2025-02-22",
  },
  {
    id: 13,
    name: "Apple Watch",
    price: 89999,
    category: "Electronics",
    stock: 18,
    status: "active",
    createdAt: "2025-02-25",
  },
  {
    id: 14,
    name: "Zara Jacket",
    price: 12999,
    category: "Clothing",
    stock: 29,
    status: "inactive",
    createdAt: "2025-02-28",
  },
  {
    id: 15,
    name: "Nintendo Switch",
    price: 49999,
    category: "Gaming",
    stock: 15,
    status: "active",
    createdAt: "2025-03-01",
  },
];

// Mock Orders (12+ items)
export const mockOrders = [
  {
    id: "ORD-001",
    customer: "Fatima Zafar",
    total: 18999,
    status: "delivered",
    date: "2025-02-01",
    items: 2,
  },
  {
    id: "ORD-002",
    customer: "Omar Raza",
    total: 285000,
    status: "shipped",
    date: "2025-02-05",
    items: 1,
  },
  {
    id: "ORD-003",
    customer: "Sana Mirza",
    total: 12999,
    status: "pending",
    date: "2025-02-10",
    items: 3,
  },
  {
    id: "ORD-004",
    customer: "Ali Hamza",
    total: 249999,
    status: "processing",
    date: "2025-02-12",
    items: 1,
  },
  {
    id: "ORD-005",
    customer: "Ayesha Khan",
    total: 34999,
    status: "delivered",
    date: "2025-02-15",
    items: 2,
  },
  {
    id: "ORD-006",
    customer: "Bilal Ahmed",
    total: 22999,
    status: "cancelled",
    date: "2025-02-18",
    items: 1,
  },
  {
    id: "ORD-007",
    customer: "Hira Tariq",
    total: 45999,
    status: "delivered",
    date: "2025-02-20",
    items: 4,
  },
  {
    id: "ORD-008",
    customer: "Usman Chaudhry",
    total: 329999,
    status: "processing",
    date: "2025-02-22",
    items: 1,
  },
  {
    id: "ORD-009",
    customer: "Zara Malik",
    total: 189999,
    status: "shipped",
    date: "2025-02-25",
    items: 1,
  },
  {
    id: "ORD-010",
    customer: "Hamza Ali",
    total: 8999,
    status: "delivered",
    date: "2025-02-28",
    items: 3,
  },
  {
    id: "ORD-011",
    customer: "Fatima Zafar",
    total: 32999,
    status: "pending",
    date: "2025-03-01",
    items: 2,
  },
  {
    id: "ORD-012",
    customer: "Omar Raza",
    total: 58999,
    status: "delivered",
    date: "2025-03-02",
    items: 1,
  },
];

// Mock Users (8 items)
export const mockUsers = [
  {
    id: 1,
    name: "Fatima Zafar",
    email: "fatima@shopcore.com",
    role: "admin",
    ordersCount: 12,
    status: "active",
    joined: "2024-09-01",
  },
  {
    id: 2,
    name: "Omar Raza",
    email: "omar@example.com",
    role: "user",
    ordersCount: 3,
    status: "active",
    joined: "2025-01-15",
  },
  {
    id: 3,
    name: "Sana Mirza",
    email: "sana@example.com",
    role: "user",
    ordersCount: 0,
    status: "blocked",
    joined: "2025-01-20",
  },
  {
    id: 4,
    name: "Ali Hamza",
    email: "ali@example.com",
    role: "user",
    ordersCount: 7,
    status: "active",
    joined: "2024-12-01",
  },
  {
    id: 5,
    name: "Ayesha Khan",
    email: "ayesha@example.com",
    role: "user",
    ordersCount: 4,
    status: "active",
    joined: "2025-02-10",
  },
  {
    id: 6,
    name: "Bilal Ahmed",
    email: "bilal@example.com",
    role: "user",
    ordersCount: 2,
    status: "inactive",
    joined: "2025-02-15",
  },
  {
    id: 7,
    name: "Hira Tariq",
    email: "hira@example.com",
    role: "admin",
    ordersCount: 8,
    status: "active",
    joined: "2024-11-20",
  },
  {
    id: 8,
    name: "Usman Chaudhry",
    email: "usman@example.com",
    role: "user",
    ordersCount: 1,
    status: "active",
    joined: "2025-02-25",
  },
];

// Mock Returns (5+ items)
export const mockReturns = [
  {
    id: "RET-001",
    orderId: "ORD-002",
    product: "Rolex Submariner",
    reason: "Defective movement",
    amount: 285000,
    date: "2025-02-20",
    status: "pending",
    customerNote: "Watch not working properly",
    refundMethod: "Bank transfer",
  },
  {
    id: "RET-002",
    orderId: "ORD-005",
    product: "Sony Headphones",
    reason: "Wrong color",
    amount: 34999,
    date: "2025-02-22",
    status: "approved",
    customerNote: "Sent black instead of white",
    refundMethod: "Original payment",
  },
  {
    id: "RET-003",
    orderId: "ORD-008",
    product: "MacBook Pro",
    reason: "Damaged",
    amount: 329999,
    date: "2025-02-25",
    status: "pending",
    customerNote: "Scratch on screen",
    refundMethod: "Store credit",
  },
  {
    id: "RET-004",
    orderId: "ORD-001",
    product: "Nike Air Max",
    reason: "Wrong size",
    amount: 18999,
    date: "2025-02-28",
    status: "rejected",
    customerNote: "Size 10 ordered, got 8",
    refundMethod: "Original payment",
  },
  {
    id: "RET-005",
    orderId: "ORD-010",
    product: "Nike Hoodie",
    reason: "Changed mind",
    amount: 8999,
    date: "2025-03-01",
    status: "completed",
    customerNote: "Didn't like the color",
    refundMethod: "Original payment",
  },
];

// Dashboard Stats
export const dashboardStats = {
  totalRevenue: 1542899,
  totalOrders: 342,
  totalUsers: 1280,
  totalProducts: 47,
};

// Weekly Sales Data for Chart
export const weeklySales = [
  { day: "Mon", sales: 124000 },
  { day: "Tue", sales: 98000 },
  { day: "Wed", sales: 210000 },
  { day: "Thu", sales: 187000 },
  { day: "Fri", sales: 256000 },
  { day: "Sat", sales: 189000 },
  { day: "Sun", sales: 143000 },
];

// Top Products
export const topProducts = [
  { id: 1, name: "Rolex Submariner", sales: 285000, units: 1 },
  { id: 2, name: "MacBook Pro", sales: 329999, units: 1 },
  { id: 3, name: "iPhone 15 Pro", sales: 249999, units: 1 },
  { id: 4, name: "Nike Air Max", sales: 18999, units: 12 },
  { id: 5, name: "Sony Headphones", sales: 34999, units: 8 },
];
